#pragma config(Sensor, S3,     colorBill,      sensorColorNxtFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void test()
{
	while (true)
	{
		displayString(0,"%i", SensorRaw[S3]);
		wait1Msec(100);
	}
}

task main()
{
	test();
}
