#pragma config(Sensor, S3,     ,               sensorEV3_Touch)
#pragma config(Sensor, S4,     ,               sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int test()
{
	while (1<2)
	{
		displayString(0,"%i", SensorValue[S4]);
		wait1Msec(100);
	}
return 1;
}

task main()
{
	test();
}
